language: cpp
os:
  - osx
before_install:
- brew update > /dev/null; brew install qt5 > /dev/null; export PATH=/usr/local/opt/qt5/bin/:$PATH
- cd ./src && ./configure && cd ./../
script:
  - git submodule update --init --recursive 
  - cd ./src
  - qmake && make -s -j 2
after_success:
  - ls -l ../bin/osx/release
